#!/usr/bin/env node
// The shared catalog is authored once; runtime copies are generated.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = file => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8'));
const catalog = read('resources/codegrid-error-messages.json');
const registry = read('spec/codegrid-error-codes.json');
const inventory = read('editors/vscode/l10n/locales.json');
if (catalog.schema !== 'codegrid.error.messages' || catalog.schema_version !== 1 ||
    catalog.registry_version !== registry.registry_version || catalog.default_locale !== inventory.default ||
    JSON.stringify(catalog.locales) !== JSON.stringify(inventory.supported)) throw new Error('Invalid catalog metadata');
if (Object.keys(catalog.errors).length !== registry.entries.length) throw new Error('Error catalog coverage mismatch');
function validate(messages) {
  if (Object.keys(messages).sort().join() !== [...catalog.locales].sort().join()) throw new Error('Locale coverage mismatch');
  for (const locale of catalog.locales) {
    if (typeof messages[locale] !== 'string' || !messages[locale].trim() || messages[locale].includes('\uFFFD')) throw new Error(`Invalid translation: ${locale}`);
    if (JSON.stringify((messages[locale].match(/\{\d+\}/g) || []).sort()) !== JSON.stringify((messages.en.match(/\{\d+\}/g) || []).sort())) throw new Error(`Translation arguments changed: ${locale}`);
  }
}
validate(catalog.fallback);
for (const entry of registry.entries) {
  const row = catalog.errors[entry.error_number];
  if (!row || row.layer !== entry.layer || row.code !== entry.code) throw new Error(`Identity mismatch: ${entry.error_number}`);
  validate(row.messages);
}
const strings = messages => catalog.locales.map(locale => JSON.stringify(messages[locale])).join(', ');
const rust = '// Generated by scripts/generate_error_messages.js; edit resources/codegrid-error-messages.json.\n' +
  '#[rustfmt::skip]\npub const ERROR_LOCALES: &[&str] = &[' + catalog.locales.map(JSON.stringify).join(', ') + '];\n' +
  '#[rustfmt::skip]\npub const ERROR_FALLBACKS: &[&str] = &[' + strings(catalog.fallback) + '];\n' +
  '#[rustfmt::skip]\npub const ERROR_MESSAGES: &[(&str, [&str; 10])] = &[\n' +
  Object.entries(catalog.errors).map(([number, row]) => `    (${JSON.stringify(number)}, [${strings(row.messages)}]),`).join('\n') + '\n];\n';
for (const [file, content] of [
  ['crates/codegrid-model/src/error_messages.rs', rust],
  ['editors/vscode/l10n/codegrid-error-messages.json', JSON.stringify(catalog, null, 2) + '\n'],
]) {
  const target = path.join(root, file);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== content) throw new Error(`Stale generated catalog: ${file}`);
  } else fs.writeFileSync(target, content);
}
console.log(`Error translations valid: ${registry.entries.length} numbers, ${catalog.locales.length} locales.`);
