#!/usr/bin/env node
// Generate presentation-only error identities from the normative registry.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const registry = JSON.parse(fs.readFileSync(path.join(root, 'spec/codegrid-error-codes.json'), 'utf8'));
const entries = registry.entries;
const seen = new Set();
for (const entry of entries) {
  if (!/^[1-9][0-9]{3}$/.test(entry.error_number) || seen.has(entry.error_number)) {
    throw new Error(`Invalid or duplicate error number: ${entry.layer}:${entry.code}`);
  }
  seen.add(entry.error_number);
}
const outputs = new Map([
  ['crates/codegrid-model/src/error_numbers.rs',
    '// Generated by scripts/generate_error_numbers.js; edit the JSON registry instead.\n' +
    '/// Stable four-digit presentation identities, scoped by original layer and code.\n' +
    '#[rustfmt::skip]\n' +
    'pub const ERROR_NUMBERS: &[(&str, &str, &str)] = &[\n' +
    entries.map(e => `    (${JSON.stringify(e.layer)}, ${JSON.stringify(String(e.code))}, ${JSON.stringify(e.error_number)}),`).join('\n') + '\n];\n'],
  ['editors/vscode/src/language/errorNumbers.ts',
    '// Generated by scripts/generate_error_numbers.js; edit the JSON registry instead.\n' +
    'export const errorNumbers: Readonly<Record<string, string>> = {\n' +
    entries.map(e => `  ${JSON.stringify(`${e.layer}:${e.code}`)}: ${JSON.stringify(e.error_number)},`).join('\n') + '\n};\n'],
  ['spec/codegrid-error-numbers.md',
    '# CodeGrid Four-Digit Error Numbers\n\n' +
    'Generated from [codegrid-error-codes.json](codegrid-error-codes.json). Numbers are stable, unique, append-only four-digit decimal strings. Original identifiers and protocol codes remain compatible.\n\n' +
    '| Number | Layer | Original code | Trigger / meaning |\n| --- | --- | --- | --- |\n' +
    entries.map(e => `| \`${e.error_number}\` | ${e.layer} | \`${e.code}\` | ${e.condition.replace(/\|/g, '\\|')} |`).join('\n') + '\n'],
]);
for (const [relative, expected] of outputs) {
  const file = path.join(root, relative);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== expected) {
      throw new Error(`Stale error-number artifact: ${relative}`);
    }
  } else {
    fs.writeFileSync(file, expected);
  }
}
