import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {memoryMaximum} from '../../codegrid-level-wasm-browser/tests/wasm-memory.mjs';
import {runLevelSmoke,runConformance} from '../../codegrid-level-wasm-browser/tests/level-smoke.mjs';
import {runNegativeTransport} from '../../codegrid-level-wasm-browser/tests/level-negative.mjs';
const root=resolve(import.meta.dirname,'../../..');
const path=resolve(root,process.env.CARGO_TARGET_DIR??'target','wasm32-unknown-unknown/release/codegrid_level_wasm_server.wasm');
const bytes=readFileSync(path),module=await WebAssembly.compile(bytes);
assert.equal(memoryMaximum(bytes),BigInt(process.env.CODEGRID_WASM_MAX_MEMORY_BYTES??'67108864'),'encoded memory maximum');
assert.deepEqual(WebAssembly.Module.imports(module),[],'portable artifact imports nothing');
const exports=(await WebAssembly.instantiate(module)).exports;
assert.equal(exports.level_abi_version(),1);
for(const name of ['memory','level_alloc','level_dealloc','level_request'])assert.ok(name in exports,name);
assert.equal(exports.level_alloc(0),0);assert.equal(exports.level_alloc(8388609),0);assert.equal(exports.level_request(1,1),0n);
assert.throws(()=>exports.memory.grow(65536),RangeError,'runtime memory ceiling');
const invalid=exports.level_alloc(1);new Uint8Array(exports.memory.buffer,invalid,1)[0]=255;const invalidPair=exports.level_request(invalid,1);const invalidPointer=Number(invalidPair>>32n),invalidLength=Number(invalidPair&0xffffffffn);assert.equal(JSON.parse(new TextDecoder().decode(new Uint8Array(exports.memory.buffer,invalidPointer,invalidLength))).error.code,'level_api.invalid_request');exports.level_dealloc(invalidPointer,invalidLength);exports.level_dealloc(invalid,1);
function transport(value,guest=exports){const text=new TextEncoder().encode(JSON.stringify(value));const p=guest.level_alloc(text.length);assert.notEqual(p,0);new Uint8Array(guest.memory.buffer,p,text.length).set(text);assert.equal(guest.level_request(p,text.length-1),0n,'exact pair');const pair=guest.level_request(p,text.length);assert.notEqual(pair,0n);const rp=Number(pair>>32n),length=Number(pair&0xffffffffn);const response=new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(guest.memory.buffer,rp,length));assert.equal(guest.level_dealloc(rp,length+1),0);assert.equal(guest.level_dealloc(rp,length),1);assert.equal(guest.level_dealloc(rp,length),0);assert.equal(guest.level_dealloc(p,text.length),1);return response;}
const envelope=(operation,fields={})=>({abi_version:1,api_version:1,operation,...fields});
assert.equal(JSON.parse(transport(envelope('request',{request_json:'{}'}))).error.code,'level_abi.not_initialized');
assert.equal(JSON.parse(transport({...envelope('shutdown'),abi_version:2})).error.code,'level_abi.unsupported_version');
const profile=readFileSync(resolve(root,'fixtures/levels/profiles/local-v1.json'),'utf8');
// Exercise aggregate/count ceilings and allocation failure before semantic dispatch.
const bufferGuest=new WebAssembly.Instance(module).exports;
const oneByteBuffers=[];
for(let index=0;index<1024;index++){const pointer=bufferGuest.level_alloc(1);assert.notEqual(pointer,0);oneByteBuffers.push(pointer);}
assert.equal(bufferGuest.level_alloc(1),0,'buffer count ceiling');
for(const pointer of oneByteBuffers)assert.equal(bufferGuest.level_dealloc(pointer,1),1);
assert.equal(JSON.parse(transport(envelope('initialize',{profile_json:profile}),bufferGuest)).status,'ok');
const reservationRequest=new TextEncoder().encode(JSON.stringify(envelope('request',{request_json:JSON.stringify({api_version:1,operation:'load_level',level_json:readFileSync(resolve(root,'fixtures/levels/echo.json'),'utf8')})})));
const reservationPointer=bufferGuest.level_alloc(reservationRequest.length);new Uint8Array(bufferGuest.memory.buffer,reservationPointer,reservationRequest.length).set(reservationRequest);
const aggregateBuffers=[bufferGuest.level_alloc(8388608),bufferGuest.level_alloc(8388608)];assert(aggregateBuffers.every(Boolean));
assert.equal(bufferGuest.level_alloc(8388608),0,'aggregate buffer byte ceiling');
assert.equal(bufferGuest.level_request(reservationPointer,reservationRequest.length),0n,'response reservation failure does not dispatch');
for(const pointer of aggregateBuffers)assert.equal(bufferGuest.level_dealloc(pointer,8388608),1);
const reservedPair=bufferGuest.level_request(reservationPointer,reservationRequest.length);assert.notEqual(reservedPair,0n);
const reservedPointer=Number(reservedPair>>32n),reservedLength=Number(reservedPair&0xffffffffn);
const reservedResponse=JSON.parse(new TextDecoder().decode(new Uint8Array(bufferGuest.memory.buffer,reservedPointer,reservedLength)));
assert.equal(reservedResponse.handle,'4294967297','failed reservation did not consume a semantic handle');
assert.equal(bufferGuest.level_dealloc(reservedPointer,reservedLength),1);assert.equal(bufferGuest.level_dealloc(reservationPointer,reservationRequest.length),1);
assert.equal(JSON.parse(transport(envelope('initialize',{profile_json:profile.replace('{','{"profile_version":1,')}))).error.code,'level_api.invalid_profile');
assert.equal(JSON.parse(transport(envelope('initialize',{profile_json:profile}))).status,'ok');
assert.equal(JSON.parse(transport(envelope('initialize',{profile_json:profile}))).error.code,'level_abi.already_initialized');
const fixture={level:readFileSync(resolve(root,'fixtures/levels/echo.json'),'utf8'),source:readFileSync(resolve(root,'fixtures/levels/echo.cg'),'utf8')};
const manifest=JSON.parse(readFileSync(resolve(root,'fixtures/levels/conformance-v1.json'),'utf8'));
const cases=manifest.cases.map(f=>({...f,level_json:readFileSync(resolve(root,'fixtures/levels',f.level),'utf8'),source:readFileSync(resolve(root,'fixtures/levels',f.program),'utf8')}));
const negative_cases=runNegativeTransport(profile_json=>{const guest=new WebAssembly.Instance(module).exports;assert.equal(JSON.parse(transport(envelope('initialize',{profile_json}),guest)).status,'ok');return{request:request_json=>transport(envelope('request',{request_json}),guest),shutdown:()=>transport(envelope('shutdown'),guest)};},profile,fixture,(condition,message)=>assert.ok(condition,message));
const results=runConformance(request_json=>transport(envelope('request',{request_json})),cases,(condition,message)=>assert.ok(condition,message));
const result=runLevelSmoke(request_json=>transport(envelope('request',{request_json})),fixture,(condition,message)=>assert.ok(condition,message));
const isolated=(await WebAssembly.instantiate(module)).exports;
assert.equal(JSON.parse(transport(envelope('initialize',{profile_json:profile}),isolated)).status,'ok');
assert.equal(JSON.parse(transport(envelope('request',{request_json:'{"api_version":1,"operation":"capabilities"}'}),isolated)).status,'ok','independent module lifecycle');
writeFileSync(resolve(root,'target/level-portable-report.json'),JSON.stringify({runtime:process.version,wasm_host:'Node WebAssembly',artifact_sha256:createHash('sha256').update(bytes).digest('hex'),profile:JSON.parse(profile),negative_cases,results,result},null,2));
console.log(`PASS: portable Level ABI v1 actual Node ${process.version}; no imports, exact pairs, wide seed, lifecycle, ExactIO fixture.`);
